def main():
    smallTsuHiraganaMap = {
        "っきゃ": "kkya",
        "っきゅ": "kkyu",
        "っきょ": "kkyo",
        "っぎゃ": "ggya",
        "っぎゅ": "ggyu",
        "っぎょ": "ggyo",
        "っしゃ": "ssha",
        "っしゅ": "sshu",
        "っしょ": "ssho",
        "っじゃ": "jja",
        "っじゅ": "jju",
        "っじょ": "jjo",
        "っちゃ": "ccha",
        "っちゅ": "cchu",
        "っちょ": "ccho",
        "っにゃ": "nnya",
        "っにゅ": "nnyu",
        "っにょ": "nnyo",
        "っひゃ": "hhya",
        "っひゅ": "hhyu",
        "っひょ": "hhyo",
        "っびゃ": "bbya",
        "っびゅ": "bbyu",
        "っびょ": "bbyo",
        "っぴゃ": "ppya",
        "っぴゅ": "ppyu",
        "っぴょ": "ppyo",
        "っみゃ": "mmya",
        "っみゅ": "mmyu",
        "っみょ": "mmyo",
        "っりゃ": "rrya",
        "っりゅ": "rryu",
        "っりょ": "rryo",
        "っか": "kka",
        "っき": "kki",
        "っく": "kku",
        "っけ": "kke",
        "っこ": "kko",
        "っが": "gga",
        "っぎ": "ggi",
        "っぐ": "ggu",
        "っげ": "gge",
        "っご": "ggo",
        "っさ": "ssa",
        "っし": "sshi",
        "っす": "ssu",
        "っせ": "sse",
        "っそ": "sso",
        "っざ": "zza",
        "っじ": "jji",
        "っず": "zzu",
        "っぜ": "zze",
        "っぞ": "zzo",
        "った": "tta",
        "っち": "cchi",
        "っつ": "ttsu",
        "って": "tte",
        "っと": "tto",
        "っだ": "dda",
        "っぢ": "ddi",
        "っづ": "ddu",
        "っで": "dde",
        "っど": "ddo",
        "っな": "nna",
        "っに": "nni",
        "っぬ": "nnu",
        "っね": "nne",
        "っの": "nno",
        "っは": "hha",
        "っひ": "hhi",
        "っふ": "ffu",
        "っへ": "hhe",
        "っほ": "hho",
        "っば": "bba",
        "っび": "bbi",
        "っぶ": "bbu",
        "っべ": "bbe",
        "っぼ": "bbo",
        "っぱ": "ppa",
        "っぴ": "ppi",
        "っぷ": "ppu",
        "っぺ": "ppe",
        "っぽ": "ppo",
        "っま": "mma",
        "っみ": "mmi",
        "っむ": "mmu",
        "っめ": "mme",
        "っも": "mmo",
        "っや": "yya",
        "っゆ": "yyu",
        "っよ": "yyo",
        "っら": "rra",
        "っり": "rri",
        "っる": "rru",
        "っれ": "rre",
        "っろ": "rro",
        "っわ": "wwa",
        "っを": "wwo"
    }

    newMap = {
        v: k for k, v in smallTsuHiraganaMap.items()
    }

    print("const smallTsuHiraganaMap = {")
    for k, v in newMap.items():
        print(f"\t\"{k}\": \"{v}\",")
    print("}")

main()